services:
  nginx:
    image: nginx:1.27
    container_name: vt-nginx-gateway
    restart: always
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro

